import { supabase,today,toast,escapeHtml as esc } from '../supabase.js?v=20260801-audit-context';
import { list,insert } from '../data.js?v=20260928-shortage';
export async function renderAdditions(root,profile){
 const [materials,branches,catalog,transfers]=await Promise.all([list('materials'),list('branches'),supabase.rpc('supplier_catalog'),supabase.rpc('pending_stock_transfers',{target_branch:profile.branch_id})]);
 if(catalog.error)throw catalog.error;if(transfers.error)throw transfers.error;
 const {suppliers,links}=catalog.data;let pending=transfers.data,lines=[];
 root.innerHTML='<style>#receipt-form [hidden]{display:none!important}</style>'+`<div class="page-intro"><div><h2>إضافات المخزون</h2><p>اختر المصدر ثم ابحث عن الأصناف وسجل الكمية المستلمة. سعر البيع مستقل عن تكلفة الشراء.</p></div></div><form class="panel" id="receipt-form"><div class="panel-body"><div class="form-grid"><div class="field"><label>التاريخ<input type="date" name="date" value="${today()}" max="${today()}" required></label></div><div class="field"><label>مصدر الإضافة<select name="source_kind"><option value="branch">المخزن الرئيسي أو فرع</option><option value="supplier">مورد</option><option value="transfer">استلام تحويل صادر مسجل</option></select></label></div><div class="field" id="supplier-field"><label>المورد<select name="supplier" required><option value="">اختر المورد</option>${suppliers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label></div><div class="field"><label>رقم الفاتورة / ملاحظات<input name="notes"></label></div></div>
 <div id="supplier-builder"><p id="source-help"></p><div class="form-grid"><div class="field"><label>بحث في الأصناف<input id="receipt-search" placeholder="اسم أو كود"></label></div><div class="field"><label>الصنف<select id="receipt-material"><option value="">اختر المورد أولًا</option></select></label></div><div class="field"><label>الكمية<input id="receipt-qty" type="number" min="0.0001" step="any"></label></div><div class="field"><label>تكلفة شراء الوحدة<input id="receipt-cost" type="number" min="0" step="any"></label></div></div><button type="button" class="btn gold" id="receipt-add">＋ أضف الصنف للإذن</button></div>
 <div id="transfer-builder" hidden><p>اختر التحويل الصادر المراد استلامه. الكمية والتكلفة تنتقلان من المصدر، ولا يُستلم التحويل مرتين.</p><div class="field"><label>التحويل<select id="receipt-transfer"></select></label></div><button type="button" class="btn gold" id="transfer-add">＋ إضافة التحويل للاستلام</button></div>
 <div id="receipt-lines" style="margin-top:18px"></div><div class="form-actions"><button type="reset" class="btn ghost">مسح الإذن</button><button type="submit" class="btn primary">حفظ إذن الإضافة</button></div></div></form>`;
 root.querySelector('#supplier-field').insertAdjacentHTML('beforebegin','<div class="field" id="source-branch-field"><label>المخزن أو الفرع المصدر<select name="source_branch"><option value="">اختر المصدر</option>'+branches.filter(b=>b.id!==profile.branch_id).map(b=>'<option value="'+b.id+'">'+esc(b.name==='Main warehouse'?'المخزن الرئيسي':b.name==='Main Store'?'المخزن الرئيسي — Main Store':b.name)+'</option>').join('')+'</select></label></div>');
 const form=root.querySelector('form'),select=root.querySelector('#receipt-material'),qty=root.querySelector('#receipt-qty'),cost=root.querySelector('#receipt-cost'),search=root.querySelector('#receipt-search');
 function materialOptions(){const q=search.value.trim().toLowerCase();const ids=new Set(links.filter(l=>l.supplier_id===form.supplier.value).map(l=>l.material_id));select.innerHTML='<option value="">اختر الصنف</option>'+materials.filter(m=>!m.archived_at&&(form.source_kind.value!=='supplier'||ids.has(m.id))&&`${m.name} ${m.code}`.toLowerCase().includes(q)).map(m=>`<option value="${m.id}">${esc(m.name)} — ${esc(m.code)} (${esc(m.unit)})</option>`).join('');cost.value='';}
 function draw(){root.querySelector('#receipt-lines').innerHTML=lines.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>الصنف</th><th>الوحدة</th><th>الكمية</th><th>تكلفة الوحدة</th><th>الإجمالي</th><th></th></tr></thead><tbody>${lines.map((l,i)=>`<tr><td>${esc(l.name)}</td><td>${esc(l.unit)}</td><td>${l.quantity}</td><td>${l.unit_cost??'غير موثقة'}</td><td>${l.unit_cost==null?'غير متاح':(l.quantity*l.unit_cost).toFixed(2)}</td><td><button type="button" class="delete-icon" data-remove="${i}">×</button></td></tr>`).join('')}</tbody></table></div>`:'<p>لا توجد أصناف في الإذن.</p>';root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{lines.splice(Number(b.dataset.remove),1);draw();});form.source_kind.disabled=lines.length>0;form.supplier.disabled=lines.length>0;form.source_branch.disabled=lines.length>0;}
 form.source_kind.onchange=()=>{const supplier=form.source_kind.value==='supplier';const linked=form.source_kind.value==='transfer';root.querySelector('#supplier-builder').hidden=linked;root.querySelector('#source-branch-field').hidden=supplier||linked;form.source_branch.required=!supplier&&!linked;cost.closest('.field').hidden=!supplier;root.querySelector('#source-help').textContent=supplier?'تظهر خامات المورد المختار فقط؛ أضف المورد وخاماته من صفحة الموردون والتسعير.':'كل الأصناف متاحة. هذا تسجيل استلام بالفرع ويحتاج مطابقة مع صادر المصدر؛ لا يخصم المصدر تلقائيًا. لو التحويل الصادر مسجل اختر استلام تحويل صادر مسجل لتجنب التكرار.';materialOptions();root.querySelector('#supplier-field').hidden=!supplier;root.querySelector('#transfer-builder').hidden=!linked;form.supplier.required=supplier;root.querySelector('#receipt-transfer').innerHTML='<option value="">اختر التحويل</option>'+pending.map(t=>`<option value="${t.id}">${esc(t.source_name)} ← ${esc(t.material_name)} — ${t.quantity} ${esc(t.unit)} — ${esc(t.date)}</option>`).join('');};
 form.supplier.onchange=materialOptions;search.oninput=materialOptions;select.onchange=()=>{cost.value=links.find(l=>l.supplier_id===form.supplier.value&&l.material_id===select.value)?.unit_cost??'';qty.focus();};
 root.querySelector('#receipt-add').onclick=()=>{const m=materials.find(m=>m.id===select.value);const supplier=form.source_kind.value==='supplier';if(!m||(supplier&&!form.supplier.value)||(!supplier&&!form.source_branch.value))return toast('اختر المصدر والصنف','warning');if(!qty.value||Number(qty.value)<=0||(supplier&&(cost.value===''||Number(cost.value)<0)))return toast('أدخل كمية موجبة وتكلفة شراء الوحدة','warning');const unitCost=supplier?Number(cost.value):null,quantity=Number(qty.value);if((supplier&&!Number.isFinite(unitCost))||!Number.isFinite(quantity))return;const existing=lines.find(l=>l.material_id===m.id&&l.unit_cost===unitCost);if(existing)existing.quantity+=quantity;else lines.push({material_id:m.id,name:m.name,unit:m.unit,quantity,unit_cost:unitCost,source_kind:supplier?'supplier':'branch',supplier_id:supplier?form.supplier.value:null,source_branch_id:supplier?null:form.source_branch.value});qty.value='';select.value='';cost.value='';search.value='';draw();};
 root.querySelector('#transfer-add').onclick=()=>{const t=pending.find(t=>t.id===root.querySelector('#receipt-transfer').value);if(!t)return toast('اختر تحويلًا','warning');if(lines.some(l=>l.transfer_record_id===t.id))return toast('التحويل موجود بالإذن','warning');lines.push({name:t.material_name,unit:t.unit,material_id:t.material_id,quantity:Number(t.quantity),unit_cost:t.unit_cost==null?null:Number(t.unit_cost),source_kind:'branch',source_branch_id:t.branch_id,transfer_record_id:t.id});draw();};
 form.onreset=()=>setTimeout(()=>{lines=[];form.supplier.disabled=false;form.source_branch.disabled=false;form.source_kind.disabled=false;form.date.value=today();form.source_kind.onchange();materialOptions();draw();},0);
 form.onsubmit=async e=>{e.preventDefault();if(!lines.length)return toast('أضف صنفًا إلى الإذن أولًا','warning');const button=form.querySelector('[type=submit]');button.disabled=true;try{const document_id=crypto.randomUUID();await insert('additions',lines.map(({name,unit,...l})=>({...l,branch_id:profile.branch_id,added_by:profile.id,date:form.date.value,document_id,notes:form.notes.value.trim()})));toast('تم حفظ الإذن ومصدره وتكلفة الشراء');await renderAdditions(root,profile);}catch(err){toast(err.message,'error');button.disabled=false;}};form.source_kind.onchange();draw();
}
