import { supabase, escapeHtml as esc, toast } from '../supabase.js?v=20260801-audit-context';
import { list } from '../data.js?v=20260927-procurement';
export async function renderProcurement(root) {
 const [materials,catalogResult]=await Promise.all([list('materials'),supabase.rpc('supplier_catalog')]);
 if(catalogResult.error)throw catalogResult.error;
 const {suppliers,links}=catalogResult.data;
 const active=materials.filter(m=>!m.archived_at).sort((a,b)=>a.name.localeCompare(b.name));
 root.innerHTML=`<style>#price-apply[hidden]{display:none!important}</style><div class="page-intro"><div><h2>الموردون وتسعير الخامات</h2><p>تكلفة شراء وحدة المخزون مستقلة عن سعر بيعها. سعر المورد اقتراح للإذن، والتكلفة الفعلية تحفظ مع الاستلام.</p></div></div>
 <section class="panel"><div class="panel-body"><h3>بيانات المورد</h3><form id="supplier-form"><div class="form-grid">
 <div class="field"><label>المورد<select name="supplier"><option value="">＋ مورد جديد</option>${suppliers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label></div>
 <div class="field"><label>الاسم<input name="supplier_name" required></label></div><div class="field"><label>رقم الهاتف<input name="phone" type="tel"></label></div><div class="field"><label>العنوان<input name="address"></label></div><div class="field"><label>ملاحظات<input name="notes"></label></div>
 </div><p>حدد الخامات التي يوردها. السعر لكل وحدة مخزون (ml / Unit / Pack...) وليس سعر العبوة إلا إذا كانت الوحدة عبوة.</p><div class="field"><label>بحث في خامات المورد<input id="supplier-search" placeholder="اسم أو كود الصنف"></label></div><div id="supplier-items" class="table-wrap" style="max-height:360px;overflow:auto"></div><div class="form-actions"><button class="btn primary">حفظ المورد والخامات</button></div></form></div></section>
 <section class="panel" style="margin-top:20px"><div class="panel-body"><h3>تسعير الخامات واستيراد Excel</h3><p>نزّل الأصناف، اكتب تكلفة وحدة المخزون، ثم ارفع الملف وراجع المعاينة. الكود يحدد الصنف؛ لا يتغير سعر البيع أو وحدة صنف موجود. ترك السعر فارغًا يستبعد السطر، والصفر يعني تكلفة صفر مقصودة.</p>
 <div class="form-actions"><button class="btn gold" id="price-export">تنزيل الأصناف للتسعير</button><button class="btn ghost" id="price-template">قالب أصناف جديدة</button><label class="btn ghost">اختيار Excel<input id="price-file" type="file" accept=".xlsx" hidden></label></div><div id="price-preview"></div><button class="btn primary" id="price-apply" hidden>اعتماد الأسعار المعروضة</button>
 <h3 style="margin-top:24px">تعديل سعر صنف واحد</h3><form id="single-price" class="form-grid"><div class="field"><label>الصنف<select name="material">${active.map(m=>`<option value="${m.id}">${esc(m.name)} — ${esc(m.code)} (${esc(m.unit)})</option>`).join('')}</select></label></div><div class="field"><label>تكلفة شراء وحدة المخزون<input name="cost" type="number" min="0" step="any" required></label></div><button class="btn primary">حفظ تكلفة الشراء</button></form>
 <h3 style="margin-top:24px">حاسبة سعر البيع المستهدف</h3><p>هامش الربح = (البيع − التكلفة) ÷ البيع. التقدير لا يشمل ضرائب أو خصومات غير مدخلة ولا يغير أسعار البيع تلقائيًا.</p><div class="form-grid" id="pricing-calculator"><div class="field"><label>تكلفة شراء الوحدة<input id="calc-cost" type="number" min="0" step="any"></label></div><div class="field"><label>الكمية المستخدمة<input id="calc-qty" type="number" min="0.0001" step="any" value="1"></label></div><div class="field"><label>مصاريف إضافية للخدمة<input id="calc-extra" type="number" min="0" step="any" value="0"></label></div><div class="field"><label>هامش الربح المستهدف %<input id="calc-margin" type="number" min="0" max="99" step="any" value="30"></label></div></div><p id="calc-result" role="status"></p></div></section>`;
 const form=root.querySelector('#supplier-form');let chosen=new Map();
 const draw=()=>{const query=root.querySelector('#supplier-search').value.trim().toLowerCase();root.querySelector('#supplier-items').innerHTML=`<table class="data-table"><thead><tr><th>يورد الصنف</th><th>الخامة / الكود</th><th>الوحدة</th><th>سعر المورد للوحدة</th></tr></thead><tbody>${active.filter(m=>`${m.name} ${m.code}`.toLowerCase().includes(query)).map(m=>`<tr><td><input type="checkbox" data-link="${m.id}" ${chosen.has(m.id)?'checked':''}></td><td>${esc(m.name)}<small class="row-sub">${esc(m.code)}</small></td><td>${esc(m.unit)}</td><td><input aria-label="سعر ${esc(m.name)}" type="number" min="0" step="any" data-price="${m.id}" value="${esc(chosen.get(m.id)??'')}" ${chosen.has(m.id)?'':'disabled'}></td></tr>`).join('')}</tbody></table>`;
 root.querySelectorAll('[data-link]').forEach(el=>el.onchange=()=>{if(el.checked)chosen.set(el.dataset.link,'');else chosen.delete(el.dataset.link);draw();});
 root.querySelectorAll('[data-price]').forEach(el=>el.oninput=()=>chosen.set(el.dataset.price,el.value));};
 form.supplier.onchange=()=>{const s=suppliers.find(s=>s.id===form.supplier.value);for(const key of ['phone','address','notes'])form.elements[key].value=s?.[key]||'';form.supplier_name.value=s?.name||'';chosen=new Map(links.filter(l=>l.supplier_id===s?.id).map(l=>[l.material_id,l.unit_cost??'']));draw();};
 root.querySelector('#supplier-search').oninput=draw;draw();
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button[type=submit],button.btn.primary');button.disabled=true;try{const {error}=await supabase.rpc('save_supplier',{supplier_data:{id:form.supplier.value,name:form.supplier_name.value.trim(),phone:form.phone.value.trim(),address:form.address.value.trim(),notes:form.notes.value.trim()},items:[...chosen].map(([material_id,unit_cost])=>({material_id,unit_cost:unit_cost===''?null:Number(unit_cost)}))});if(error)throw error;toast('تم حفظ المورد والخامات');await renderProcurement(root);}catch(err){toast(err.message,'error');button.disabled=false;}};
 async function download(rows,name){const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('تسعير الخامات',{views:[{rightToLeft:true}]});ws.addRow(['code','name','unit','category','cost_price']);rows.forEach(m=>ws.addRow([m.code,m.name,m.unit,m.category||'',m.cost_price>0?m.cost_price:'']));ws.columns.forEach((c,i)=>c.width=i===1?48:22);ws.getRow(1).font={bold:true};const url=URL.createObjectURL(new Blob([await wb.xlsx.writeBuffer()]));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 root.querySelector('#price-export').onclick=()=>download(active,'تسعير-الخامات.xlsx');root.querySelector('#price-template').onclick=()=>download([],'قالب-خامات.xlsx');
 let preview=[];root.querySelector('#price-file').onchange=async e=>{preview=[];root.querySelector('#price-apply').hidden=true;try{const file=e.target.files[0];if(!file)return;const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.worksheets[0];if(!ws)throw Error('الملف بدون شيت');const header=ws.getRow(1).values.slice(1).map(v=>String(v??'').trim());for(const key of ['code','name','unit','cost_price'])if(!header.includes(key))throw Error(`العمود ${key} مطلوب`);const seen=new Set();ws.eachRow((row,i)=>{if(i===1)return;const obj=Object.fromEntries(header.map((h,j)=>[h,row.getCell(j+1).value??'']));if(String(obj.cost_price).trim()==='')return;for(const key of ['code','name','unit']){if(typeof obj[key]==='object')throw Error(`خانة مركبة أو معادلة في السطر ${i}`);obj[key]=String(obj[key]).trim();if(!obj[key])throw Error(`السطر ${i}: ${key} مطلوب`);}if(typeof obj.cost_price==='object'||!Number.isFinite(Number(obj.cost_price))||Number(obj.cost_price)<0)throw Error(`سعر غير صالح في السطر ${i}`);obj.cost_price=Number(obj.cost_price);obj.code=obj.code.toUpperCase();if(seen.has(obj.code))throw Error(`كود مكرر ${obj.code}`);seen.add(obj.code);const existing=materials.find(m=>m.code.toUpperCase()===obj.code);if(existing&&existing.unit!==obj.unit)throw Error(`الوحدة مختلفة للصنف ${obj.code}`);preview.push({...obj,status:existing?'تحديث التكلفة فقط':'صنف جديد'});});if(!preview.length)throw Error('لا توجد أسعار لإضافتها');root.querySelector('#price-preview').innerHTML=`<p>${preview.length} صنف — راجع ثم اعتمد. العملية كاملة أو لا تحفظ أي سطر عند الخطأ.</p><div class="table-wrap" style="max-height:350px;overflow:auto"><table class="data-table"><thead><tr><th>الكود</th><th>الاسم</th><th>الوحدة</th><th>تكلفة الوحدة</th><th>الإجراء</th></tr></thead><tbody>${preview.map(r=>`<tr><td>${esc(r.code)}</td><td>${esc(r.name)}</td><td>${esc(r.unit)}</td><td>${r.cost_price}</td><td>${r.status}</td></tr>`).join('')}</tbody></table></div>`;root.querySelector('#price-apply').hidden=false;}catch(err){preview=[];root.querySelector('#price-preview').textContent=err.message;toast(err.message,'error');}};
 root.querySelector('#price-apply').onclick=async e=>{e.target.disabled=true;try{const {data,error}=await supabase.rpc('import_material_prices',{rows:preview});if(error)throw error;toast(`تم حفظ تكلفة ${data} صنف دون تغيير أسعار البيع`);await renderProcurement(root);}catch(err){toast(err.message,'error');e.target.disabled=false;}};
 const single=root.querySelector('#single-price');const fillPrice=()=>{const m=active.find(m=>m.id===single.material.value);single.cost.value=m?.cost_price??'';root.querySelector('#calc-cost').value=m?.cost_price??'';calculate();};single.material.onchange=fillPrice;
 single.onsubmit=async e=>{e.preventDefault();const m=active.find(m=>m.id===single.material.value);const button=single.querySelector('button');button.disabled=true;try{const {error}=await supabase.rpc('import_material_prices',{rows:[{code:m.code,name:m.name,unit:m.unit,category:m.category,cost_price:Number(single.cost.value)}]});if(error)throw error;toast('تم حفظ تكلفة الشراء؛ سعر البيع مستقل');await renderProcurement(root);}catch(err){toast(err.message,'error');button.disabled=false;}};
 function calculate(){const values=['cost','qty','extra','margin'].map(k=>root.querySelector(`#calc-${k}`).value);const [cost,qty,extra,margin]=values.map(Number);const out=root.querySelector('#calc-result');if(values.some(v=>v==='')||cost<0||qty<=0||extra<0||margin<0||margin>=100){out.textContent='أدخل تكلفة وكمية وهامشًا بين صفر وأقل من 100%';return;}const total=cost*qty+extra,price=total/(1-margin/100);out.textContent=`التكلفة الإجمالية ${total.toFixed(2)} ج.م — سعر البيع المستهدف ${price.toFixed(2)} ج.م — الربح المستهدف ${(price-total).toFixed(2)} ج.م`;}root.querySelector('#pricing-calculator').oninput=calculate;fillPrice();
}
